using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using examedu.DTO.AccountDTO;
using examedu.Services.Account;
using ExamEdu.DTO;
using ExamEdu.DTO.PaginationDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace examedu.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    public class AccountController : ControllerBase
    {
        private readonly IAccountService _accountService;
        private readonly IMapper _mapper;

       
        public AccountController(IAccountService accountService, IMapper mapper)
        {
            _accountService = accountService;
            _mapper = mapper;
        }

        /// <summary>
        /// Get the list of account in the db with pagination config
        /// </summary>
        /// <param name="paginationParameter">Pagination parameters from client</param>
        /// <returns>200: List of account with pagination / 404: search username not found</returns>
        [HttpGet("list")]
        public ActionResult<PaginationResponse<IEnumerable<AccountResponse>>> GetAccountList([FromQuery] PaginationParameter paginationParameter)
        {
            (int totalRecord, IEnumerable<AccountResponse> listAccount) =  _accountService.GetAccountList(paginationParameter);

            if (totalRecord == 0)
            {
                return NotFound(new ResponseDTO(404, "Search email not found"));
            }

            return Ok(new PaginationResponse<IEnumerable<AccountResponse>>(totalRecord, listAccount));
        }

        /// <summary>
        /// Get the list of account in the db with pagination config
        /// </summary>
        /// <param name="paginationParameter">Pagination parameters from client</param>
        /// <returns>200: List of account with pagination / 404: search username not found</returns>
        [HttpGet("deactivatedList")]
        public ActionResult<PaginationResponse<IEnumerable<AccountResponse>>> GetDeactivatedAccountList([FromQuery] PaginationParameter paginationParameter)
        {
            (int totalRecord, IEnumerable<AccountResponse> listAccount) =  _accountService.GetDeactivatedAccountList(paginationParameter);

            if (totalRecord == 0)
            {
                return NotFound(new ResponseDTO(404, "Search email not found"));
            }

            return Ok(new PaginationResponse<IEnumerable<AccountResponse>>(totalRecord, listAccount));
        }

        /// <summary>
        /// Insert new account to db, send email with password generated by system to that user
        /// </summary>
        /// <param name="accountInput">Detail of account</param>
        /// <returns>201: Created / 409: Username || email || phone is existed</returns>
        [HttpPost]
        public async Task<ActionResult> CreateNewAccount([FromBody] AccountInput accountInput)
        {
            int addResult= await _accountService.InsertNewAccount(accountInput);
            if(addResult == 0)
            {
                return Conflict(new ResponseDTO(409, "The email is existed"));
            }
            if(addResult ==-1)
            {
                return BadRequest(new ResponseDTO(400, "Error when add account"));
            }
            return CreatedAtAction(nameof(GetAccountList), new ResponseDTO(201, "Successfully inserted"));
        }

                /// <summary>
        /// Deactivate an account in the db
        /// </summary>
        /// <param name="id">Id of that account</param>
        /// <param name="role">Role of that account</param>
        /// <returns>200: Deleted / 404: Id not found</returns>
        [HttpDelete("{id:int}/{role:int}")]
        public async Task<ActionResult> DeactivateAccount(int id, int role)
        {
            int result = await _accountService.DeactivateAccount(id, role);

            if (result == -1)
            {
                return NotFound(new ResponseDTO(404, "Id not found!"));
            }
            if (result == 0)
            {
                return BadRequest(new ResponseDTO(400, "Deactivate failed"));
            }
            return Ok(new ResponseDTO(200, "Deleted!"));
        }
    }
}